name: Test
on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: yarn lint

  test:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: yarn test

  test-type:
    name: Type checking
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: yarn test:type

  test-example-apps:
    name: Test example app
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        example: ['browser-url-import', 'publicodes-react']
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: |
          cd ./examples/${{ matrix.example }}
          yarn install
          yarn test

  test-packages-versioning:
    name: Enforce consistent package versioning
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npx zx ./.github/scripts/enforce-versions.mjs
